server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
  instance:
    appname: GATEWAY-SERVICE

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/**
#            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
